# # If you change something, also update mocks

# # 'Document' will be appended to the name of the query in the generated output

# # - Fragments ----------

# fragment IdeaFields on Idea {
#   id
#   createdAt
#   content
# }

# fragment IdeaAuthorFields on Idea {
#   ...IdeaFields
#   author {
#     id
#   }
# }

# # - Queries ----------

# query ReadIdea($id: ID!) {
#   idea(id: $id) {
#     ...IdeaAuthorFields
#   }
# }

# query ReadIdeas {
#   ideas {
#     ...IdeaAuthorFields
#   }
# }

# query ReadIdeasClient {
#   ideas @client {
#     ...IdeaAuthorFields
#   }
# }

# query ReadIdeasPaginatedOffset($offset: Int!, $limit: Int!) {
#   ideasPaginatedOffset(offset: $offset, limit: $limit) {
#     ...IdeaAuthorFields
#   }
# }

# query ReadIdeasPaginatedCursor($after: String, $pageSize: Int!) {
#   ideasPaginatedCursor(after: $after, pageSize: $pageSize) {
#     cursor
#     hasMore
#     ideas {
#       ...IdeaAuthorFields
#     }
#   }
# }

# query CurrentUserIdeas {
#   currentUserIdeas {
#     ...IdeaAuthorFields
#   }
# }

# # - Mutations ----------

# mutation CreateIdea($content: String!) {
#   createIdea(content: $content) {
#     ...IdeaFields
#   }
# }

# mutation UpdateIdea($id: ID!, $content: String!) {
#   updateIdea(id: $id, content: $content) {
#     ...IdeaFields
#   }
# }

# mutation RemoveIdea($id: ID!) {
#   removeIdea(id: $id) {
#     id
#   }
# }

# mutation DeleteIdea($id: ID!) {
#   deleteIdea(id: $id) {
#     id
#   }
# }
