# If you change something, also update mocks

# 'Document' will be appended to the name of the query in the generated output

# - Fragments ----------

fragment userFields on User {
  id
  email
  role
  ideas {
    id
    content
  }
}

# - Queries ----------

# query IsLoggedIn {
#   isLoggedIn @client
# }

query ReadUser($id: ID!) {
  user(id: $id) {
    ...userFields
  }
}

query ReadUsers {
  users {
    ...userFields
  }
}

query CurrentUser {
  currentUser {
    ...userFields
  }
}

# - Mutations ----------

mutation LogIn($email: String!, $password: String!) {
  logIn(input: { email: $email, password: $password }) {
    user {
      ...userFields
    }
  }
}

mutation LogOut {
  logOut
}

mutation SignUp($email: String!, $password: String!) {
  signUp(input: { email: $email, password: $password }) {
    user {
      ...userFields
    }
  }
}

mutation PassResetReq($email: String!) {
  passResetReq(email: $email)
}

mutation PassReset($resetPassToken: String!, $newPassword: String!) {
  passReset(resetPassToken: $resetPassToken, newPassword: $newPassword) {
    user {
      ...userFields
    }
  }
}
